# Change these first
owner: NCU-CSIE-SNMG # Your GitHub organization or username, where this repository lives
repo: uptime # The name of this repository

sites:
  - name: CSIE Website
    url: https://www.csie.ncu.edu.tw
  - name: CEECS Website
    url: https://www.ceecs.ncu.edu.tw
  - name: CSIE Classroom Website
    url: https://classroom.csie.ncu.edu.tw
  - name: CSIE DNS master
    check: "tcp-ping"
    url: 140.115.50.1
    port: 53
  - name: CSIE DNS slave
    check: "tcp-ping"
    url: 140.115.50.2
    port: 53

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /uptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: NCU CSIE SNMG service uptime monitor
  navbar:
    - title: Status
      href: /uptime
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
